#!/bin/bash

GADGET_NAME="template"

USB_GADGETS=/sys/kernel/config/usb_gadget/
GADGET=$USB_GADGETS$GADGET_NAME

mkdir -p $GADGET
echo 0x1d6b > $GADGET/idVendor # Linux Foundation
echo 0x0104 > $GADGET/idProduct # Multifunction Composite Gadget
echo 0x0100 > $GADGET/bcdDevice # v1.0.0
echo 0x0200 > $GADGET/bcdUSB # USB2

mkdir -p $GADGET/strings/0x409
echo "fedcba9876543210" > $GADGET/strings/0x409/serialnumber
echo "Josef Monje" > $GADGET/strings/0x409/manufacturer
echo $GADGET_NAME > $GADGET/strings/0x409/product

mkdir -p $GADGET/configs/c.1/strings/0x409
echo "Config 1: ECM network" > $GADGET/configs/c.1/strings/0x409/configuration
echo 250 > $GADGET/configs/c.1/MaxPower

## Add functions
## End functions

ls /sys/class/udc > UDC
