#!/bin/bash

# Ethernet functions
mkdir -p $GADGET/functions/ecm.usb0
# first byte of address must be even
HOST="48:6f:73:74:50:43" # "HostPC"
SELF="50:69:5a:65:72:6f" # "PiZero"
echo $HOST > $GADGET/functions/ecm.usb0/host_addr
echo $SELF > $GADGET/functions/ecm.usb0/dev_addr
ln -s $GADGET/functions/ecm.usb0 $GADGET/configs/c.1/
