#!/bin/bash

# Mass storage functions
FILE=/home/pi/zero-gadgets/disk.img
mkdir -p ${FILE/img/d}
# mount -o loop,ro,offset=1048576 -t ext4 $FILE ${FILE/img/d} # FOR OLD WAY OF MAKING THE IMAGE
mount -o loop,ro, -t vfat $FILE ${FILE/img/d} # FOR IMAGE CREATED WITH DD

mkdir -p $GADGET/functions/mass_storage.usb0
echo 1 > $GADGET/functions/mass_storage.usb0/stall
echo 0 > $GADGET/functions/mass_storage.usb0/lun.0/cdrom
echo 0 > $GADGET/functions/mass_storage.usb0/lun.0/ro
echo 0 > $GADGET/functions/mass_storage.usb0/lun.0/nofua
echo $FILE > $GADGET/functions/mass_storage.usb0/lun.0/file
ln -s $GADGET/functions/mass_storage.usb0 $GADGET/configs/c.1/
