#!/bin/sh
#
# Linux UVC gadget driver bug
# https://www.mail-archive.com/linux-usb@vger.kernel.org/msg89422.html
#

# Webcam functions
mkdir -p $GADGET/functions/uvc.usb0

CONTROL=$GADGET/functions/uvc.usb0/control
STREAMING=$GADGET/functions/uvc.usb0/streaming
mkdir -p $CONTROL/header/h
mkdir -p $CONTROL/class/fs
mkdir -p $CONTROL/class/ss
mkdir -p $STREAMING/header/h
mkdir -p $STREAMING/class/fs
mkdir -p $STREAMING/class/ss
ln -s $CONTROL/header/h $CONTROL/class/fs
ln -s $CONTROL/header/h $CONTROL/class/ss
ln -s $STREAMING/header/h $STREAMING/class/fs
ln -s $STREAMING/header/h $STREAMING/class/ss

mkdir -p $STREAMING/uncompressed/u/360p

cat > $STREAMING/uncompressed/u/360p/dwFrameInterval <<- EOM
666666
1000000
5000000
EOM

echo 2048 > $GADGET/functions/uvc.usb0/streaming_maxpacket
ln -s $GADGET/functions/uvc.usb0 $GADGET/configs/c.1/
