#!/bin/bash

# Webcam functions
mkdir -p $GADGET/functions/uvc.usb0/streaming/uncompressed/u/360p
cat << EOF > $GADGET/functions/uvc.usb0/streaming/uncompressed/u/360p/dwFrameInterval
666666
1000000
5000000
EOF

mkdir -p $GADGET/functions/uvc.usb0/streaming/header/h
ln -s $GADGET/functions/uvc.usb0/streaming/header/h $GADGET/functions/uvc.usb0/streaming/uncompressed/u
ln -s $GADGET/functions/uvc.usb0/streaming/class/fs $GADGET/functions/uvc.usb0/streaming/header/h
ln -s $GADGET/functions/uvc.usb0/streaming/class/hs $GADGET/functions/uvc.usb0/streaming/header/h

mkdir -p $GADGET/functions/uvc.usb0/control/header/h
mkdir -p $GADGET/functions/uvc.usb0/control/class/fs
mkdir -p $GADGET/functions/uvc.usb0/control/class/ss
ln -s $GADGET/functions/uvc.usb0/control/header/h $GADGET/functions/uvc.usb0/control/class/fs
ln -s $GADGET/functions/uvc.usb0/control/header/h $GADGET/functions/uvc.usb0/control/class/ss

echo 2048 > functions/uvc.usb0/streaming_maxpacket
ln -s $GADGET/functions/uvc.usb0 $GADGET/configs/c.1/
